import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  HomeOutline,
  TeamOutline,
  ProfileOutline,
  SendOutline,
  SolutionOutline,
  InboxOutline,
  BarChartOutline,
  BankOutline,
  UserOutline,
  LogoutOutline,
  ArrowLeftOutline,
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  HomeOutline,
  TeamOutline,
  ProfileOutline,
  SendOutline,
  SolutionOutline,
  InboxOutline,
  BarChartOutline,
  BankOutline,
  UserOutline,
  LogoutOutline,
  ArrowLeftOutline,
];
